=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Anticheat",
  "description": "Schema for anticheat entries.",
  "type": "object",
  "required": ["platform", "status", "versions", "price"],
  "properties": {
    "platform": {
      "type": ["string", "array"],
      "default": "Unknown",
      "anyOf": [
        {
          "$ref": "#/$defs/multiple-platforms"
        },
        {
          "const": "Unknown"
        }
      ]
    },
    "status": {
      "type": ["string", "null"],
      "default": "Unknown",
      "enum": ["Active", "Inactive", "Discontinued", "Unknown", "Old", "Unavailable", null]
    },
    "versions": {
      "type": "string",
      "default": "Unknown",
      "minLength": 1
    },
    "spigot": {
      "type": ["integer", "null"],
      "default": null
    },
    "github": {
      "type": ["string", "null"],
      "default": null,
      "pattern": "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$"
    },
    "price": {
      "type": "string",
      "anyOf": [
        {},
        {
          "const": "Free"
        }
      ]
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": ["string", "null"],
            "anyOf": [
              {},
              {
                "enum": [
                  "GitHub",
                  "SpigotMC",
                  "Bukkit",
                  "BuiltByBit",
                  "Discord",
                  "Dedicated Site",
                  "BStats",
                  "Hangar",
                  "Polymart"
                ]
              }
            ]
          },
          "url": {
            "$ref": "#/$defs/url"
          }
        },
        "required": ["name", "url"],
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false,
  "$defs": {
    "single-platform": {
      "type": "string",
      "enum": [
        "Bukkit",
        "Sponge",
        "Skript",
        "Minestom",
        "Datapack",
        "Fabric",
        "Forge"
      ]
    },
    "multiple-platforms": {
      "anyOf": [
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/single-platform"
          },
          "uniqueItems": true,
          "minItems": 1
        },
        {
          "$ref": "#/$defs/single-platform"
        }
      ]
    },
    "url": {
      "type": "string",
      "format": "uri",
      "pattern": "^https?://.*$"
    }
  }
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Spiter Anticheat.json
{
  "platform": "Bukkit",
  "status": "Active",
  "versions": "1.8 - 1.20.2",
  "spigot": null,
  "github": null,
  "price": "€69.99 (EUR)",
  "links": [
    {
      "name": "Discord",
      "url": "https://discord.gg/TErzKwGUEc"
    },
    {
      "name": "BStats",
      "url": "https://bstats.org/plugin/bukkit/Spiter/19535"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/RegotlyLong/SpiterAnticheat"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/AntiCheatPlus.json
{
  "platform": "Bukkit",
  "status": null,
  "versions": "1.7",
  "spigot": 2714,
  "github": "m1enkrafftman/AntiCheatPlus",
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/2714"
    },
    {
      "name": "Bukkit",
      "url": "https://dev.bukkit.org/projects/anticheatplus"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/m1enkrafftman/AntiCheatPlus"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Verus.json
{
  "platform": "Bukkit",
  "status": "Old",
  "versions": "1.7 - 1.20.1",
  "spigot": null,
  "github": null,
  "price": "$60.00, $125.00, $200.00 (?)",
  "links": [
    {
      "name": "Dedicated Site",
      "url": "https://verus.ac"
    },
    {
      "name": "Discord",
      "url": "https://discord.gg/G9RGfuZ"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Knockback++.json
{
  "platform": "Bukkit",
  "status": null,
  "versions": "1.8",
  "spigot": 36140,
  "github": "hugo4715/KnockbackPlusPlus",
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/36140"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/hugo4715/KnockbackPlusPlus"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/LightAntiCheat (by Vekster).json
{
  "platform": "Bukkit",
  "status": null,
  "versions": "1.8 - 1.21",
  "spigot": 112053,
  "github": null,
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/112053"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/tiredvekster/LightAntiCheat"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/BaritoneRemover.json
{
  "platform": "Bukkit",
  "status": null,
  "versions": "1.8 – 26.1.2",
  "spigot": 112430,
  "github": "ChromMob/BaritoneRemover",
  "price": "Free",
  "links": [
    {
      "name": "GitHub",
      "url": "https://github.com/ChromMob/BaritoneRemover"
    },
    {
      "name": "Modrinth",
      "url": "https://modrinth.com/plugin/baritoneremover"
    },
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/112430"
    },
    {
      "name": "Discord",
      "url": "https://discord.gg/xG8beHPXUS"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Negativity v1.json
{
  "platform": "Bukkit",
  "status": "Discontinued",
  "versions": "1.8 - 1.20.1",
  "spigot": 48399,
  "github": null,
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/48399"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/Elikill58/Negativity"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/VerdantAC.json
{
  "platform": "Bukkit",
  "status": "Active",
  "versions": "1.8 - 1.21.11",
  "spigot": null,
  "github": null,
  "price": "Contact for info",
  "links": [
    {
      "name": "Dedicated Site",
      "url": "https://verdantstudios.xyz"
    },
    {
      "name": "Discord",
      "url": "https://dc.gg/verdantstudios"
    }
  ]
}
