=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Anticheat",
  "description": "Schema for anticheat entries.",
  "type": "object",
  "required": ["platform", "status", "versions", "price"],
  "properties": {
    "platform": {
      "type": ["string", "array"],
      "default": "Unknown",
      "anyOf": [
        {
          "$ref": "#/$defs/multiple-platforms"
        },
        {
          "const": "Unknown"
        }
      ]
    },
    "status": {
      "type": ["string", "null"],
      "default": "Unknown",
      "enum": ["Active", "Inactive", "Discontinued", "Unknown", "Old", "Unavailable", null]
    },
    "versions": {
      "type": "string",
      "default": "Unknown",
      "minLength": 1
    },
    "spigot": {
      "type": ["integer", "null"],
      "default": null
    },
    "github": {
      "type": ["string", "null"],
      "default": null,
      "pattern": "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$"
    },
    "price": {
      "type": "string",
      "anyOf": [
        {},
        {
          "const": "Free"
        }
      ]
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": ["string", "null"],
            "anyOf": [
              {},
              {
                "enum": [
                  "GitHub",
                  "SpigotMC",
                  "Bukkit",
                  "BuiltByBit",
                  "Discord",
                  "Dedicated Site",
                  "BStats",
                  "Hangar",
                  "Polymart"
                ]
              }
            ]
          },
          "url": {
            "$ref": "#/$defs/url"
          }
        },
        "required": ["name", "url"],
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false,
  "$defs": {
    "single-platform": {
      "type": "string",
      "enum": [
        "Bukkit",
        "Sponge",
        "Skript",
        "Minestom",
        "Datapack",
        "Fabric",
        "Forge"
      ]
    },
    "multiple-platforms": {
      "anyOf": [
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/single-platform"
          },
          "uniqueItems": true,
          "minItems": 1
        },
        {
          "$ref": "#/$defs/single-platform"
        }
      ]
    },
    "url": {
      "type": "string",
      "format": "uri",
      "pattern": "^https?://.*$"
    }
  }
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Grim.json
{
  "platform": [
    "Bukkit",
    "Fabric"
  ],
  "status": null,
  "versions": "1.8.8 - 26.2",
  "spigot": 99923,
  "github": "GrimAnticheat/Grim",
  "price": "Free",
  "links": [
    {
      "name": "Modrinth",
      "url": "https://modrinth.com/plugin/grimac"
    },
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/99923"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/GrimAnticheat/Grim"
    },
    {
      "name": "Hanger",
      "url": "https://hangar.papermc.io/GrimAnticheat/GrimAnticheat"
    },
    {
      "name": "Dedicated Site",
      "url": "https://grim.ac"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/AntiHaxerman.json
{
  "platform": "Bukkit",
  "status": null,
  "versions": "1.8.8",
  "spigot": 83198,
  "github": "Tecnio/AntiHaxerman",
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/83198"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/Tecnio/AntiHaxerman"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Daedalus.json
{
  "platform": "Bukkit",
  "status": "Discontinued",
  "versions": "1.7 - 1.13",
  "spigot": 49215,
  "github": "funkemunky/Daedalus",
  "price": "Free",
  "links": [
    {
      "name": "GitHub",
      "url": "https://github.com/funkemunky/Daedalus"
    },
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/49215"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Vulcan.json
{
  "platform": "Bukkit",
  "status": null,
  "versions": "1.8 - 26.2",
  "spigot": 83626,
  "github": null,
  "price": "$19.99 (USD)",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/83626"
    },
    {
      "name": "Discord",
      "url": "https://discord.com/invite/SCNuwUG"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Hades.json
{
  "platform": "Bukkit",
  "status": "Inactive",
  "versions": "1.7 - 1.15",
  "spigot": 65622,
  "github": "Tecnio/Hades",
  "price": "Free",
  "links": [
    {
      "name": "GitHub",
      "url": "https://github.com/Tecnio/Hades"
    },
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/65622"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Astro.json
{
  "platform": "Bukkit",
  "status": "Active",
  "versions": "1.8+",
  "spigot": null,
  "github": null,
  "price": "$30.00 (?)",
  "links": [
    {
      "name": "Dedicated Site",
      "url": "https://astroac.gg"
    },
    {
      "name": "Discord",
      "url": "https://discord.gg/fJGspEJnyh"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/ThotPatrol.json
{
  "platform": "Bukkit",
  "status": "Discontinued",
  "versions": "1.7 - 1.8",
  "spigot": 79978,
  "github": "freppp/ThotPatrol",
  "price": "Free",
  "links": [
    {
      "name": "SpigotMC",
      "url": "https://spigotmc.org/resources/79978"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/freppp/ThotPatrol"
    }
  ]
}

=== ManInMyVan/Minecraft-Anticheat-List/src/jsMain/resources/anticheats/Shard.json
{
  "platform": "Bukkit",
  "status": null,
  "spigot": null,
  "github": "KaelusAI/Shard",
  "versions": "1.8.8 - 26.2",
  "price": "Free, $19.90/mo, $29.90/mo, $39.90/mo, $59.90/mo, $89.90/mo (USD)",
  "links": [
    {
      "name": "Dedicated Site",
      "url": "https://shard.ac/"
    },
    {
      "name": "GitHub",
      "url": "https://github.com/KaelusAI/Shard"
    },
    {
      "name": "Discord",
      "url": "https://discord.gg/kaelus"
    }
  ]
}
